databases:
  - name: bookface
    databaseName: bookface
    user: bookface

services:
  - type: web
    name: bookface
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookface
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false